### ISSUE TITLE
require is not defined in ES module scope

### ISSUE THREAD

**Issue by entity** [lepikhinb/vite-plugin-watch#6]
Hey there,

Just bought your book and setting up this plugin, I get this error:
```
failed to load config from /Users/charlie/Downloads/test-ts/vite.config.ts
error when starting dev server:
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///Users/charlie/Downloads/test-ts/node_modules/vite-plugin-watch/dist/vite-plugin-watch.js:429:20
```

Any reason why?

**Comment by michaelsieminski** [comment]
made a PR for a fix [here](https://github.com/lepikhinb/vite-plugin-watch/pull/7)

**Comment by pardmeister** [comment]
Not sure why but I'm getting this error again.
```
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///Users/kabelo/workspace/code/sites/scaffold/node_modules/vite-plugin-watch/dist/vite-plugin-watch.js:429:20
```

**Comment by loreias** [comment]
Same issue here. The build does not include the PR fix done by 1CAMOU. I'm trying to build it locally but I'm getting some problems while doing so.

**Comment by lepikhinb** [comment]
This should be resolved now. Let me know if anything goes wrong.
