### ISSUE TITLE
0.3 does not contain built sources

### ISSUE THREAD

**Issue by Propaganistas** [lepikhinb/vite-plugin-watch#9]
Opening this as an issue because my reply in the merged PR might not be triggering a notification:

https://github.com/lepikhinb/vite-plugin-watch/pull/8#issuecomment-1994249994

When downloading v0.3 it seems that the plugin files in `dist` do not include the new code pieces. Perhaps you forgot to build the new sources before publishing it to NPM?

**Comment by lepikhinb** [comment]
Should be good now, thanks!
